name: flutter_cdg_karaoke_player
description: Flutter CDG Karaoke Player

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.27
  logger: ^1.1.0
  dio: ^4.0.4
  dio_http2_adapter: ^2.0.0
  pretty_dio_logger: ^1.1.1
  audio_session: ^0.1.9
  just_audio_windows: ^0.1.0
  get: ^4.6.5
  archive: ^3.3.0
  image: ^3.2.0
  bitmap: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - 'assets/cdg/'
